/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUxxZGdOUHFmK2t3L2taSXdIU2t1RHJlN3VQVjMxdlQ1OSs5T0xkY2drTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid1JxMnY1a3g4RGFTczY3ZENxS1ZxK0d3T3ZnVWVjZG5RUTlFSGw1M0tGaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5QlZuc2FCdlhMS3dwSktERThRcSs3V2ZEMTcrSFRsOVVrZTRzb3BYQ2xJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5cUFSLzFobCt5ditBSXQvYXZhUzliTTdhUm1RQnpBZUxjbW9VT0Qyd3hRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVNeFN3VHkxS3lRRmhaT2ZQREZNOHh3RmY3YzZXSGxpNzk1UHRDNHNEWGM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpzQUhUSTlCNVdsOU5FWWpjTnQ5M240cWpmZE42NDlLWXJQQ09LZDhKVDA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0cvY1VFbTMvN1lyUTNPaitCeC9XSFQ1RkJFeGQ5SEZuZ2xVWFBDVXNsST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieis3VGh2WFEvaWlHUDNsaS9LNDRTWnZtajRhVW9ESnlEZ080R3ovUXFuND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJEQmF2ZjYzS3k5eXRNNE93YndUSytzNmVBNytzRjNKMmlDN0tncThEWGhOL25rdmYzZ1NibWZaSi9hWjJDNU8yNmh2RzZQOXg1WG5Mc2lKOW54bWhnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTQwLCJhZHZTZWNyZXRLZXkiOiJSSUJmK2s4T3IySU1aZURVSnNIM01tMkdsckVzYjREckE3cGFoRU9qeVNVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2Mzc3MTExMDgwNEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBREY3ODdGNTQ5OEVDMUEzMTBFMjNEM0E5RjIyOUVBNiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI5ODg4NDM2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNjM3NzExMTA4MDRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzYxMjEwN0FCMDZDNzhBNzZCMkZDNzgyMjIzMjlERkQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyOTg4ODQ0NH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiak1tYUR3eHZUVVM3UjUydUJxaXRVdyIsInBob25lSWQiOiI1ZjI0MDc1Ni1kZDRiLTRjODEtODMwMS1iNWQzYWViMWRlZjQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNWhaUGdDdDJyWUEvdmRVdExZZ0w3d2dLQUtzPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZndjNQTzFWaFFCemdtK1Z5eDg2OXhxbDM0az0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiI1Sk1aTTU0NCIsIm1lIjp7ImlkIjoiMjYzNzcxMTEwODA0OjNAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi4pqh8J+UpfCdkJLwnZCT8J2QkfCdkIjwnZCK8J2QhPCdkJHwnZCB8J2QjvCdkJjKt+G1ksqzy6HhtYjwn5Sl4pqhIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNLS2oxMGdRazRId3VBWVlBeUFBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJybkQwNEtLOWZkUmtnV1RpVEtnOGlsN3RTRElaRTU2L3lwSXdwbjhoc2gwPSIsImFjY291bnRTaWduYXR1cmUiOiJyWkNudjRlK0RsbFhoamhtWDBnZGgwek90LzV1WUswaHlkMThmbkNwMTRNSjdHU2ZZYTl4MnZWUlovaCttQkFsS1hCZ2VSV1JoTXJwRjBXalhGbXRCZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiSitmdE1VZ3BBa2IzMlZ6TldzdVh5cjJzY3JjNTVUWVRZUXRFSjVOakNSa2t5U1lQVWJhaFZBMHhVQTFEOFEvS2xQdlJGSEhRR3RDVTJUUE5OQmdVaUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNjM3NzExMTA4MDQ6M0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJhNXc5T0NpdlgzVVpJRms0a3lvUElwZTdVZ3lHUk9ldjhxU01LWi9JYklkIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI5ODg4NDE3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU9yNCJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'strikerboy';
const packname = process.env.PACKNAME || 'strikerboy bot';
const dev = process.env.DEV || '263771110804';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
